[project]
name = 'Decentralized-Rare-Musical-Instrument-Authentication'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.condition-assessment]
path = 'contracts/condition-assessment.clar'
clarity_version = 2
epoch = 2.5

[contracts.maker-verification]
path = 'contracts/maker-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
